<?php

namespace AppBundle\Repository;

/**
 * TimeslotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeslotsRepository extends \Doctrine\ORM\EntityRepository
{
}
